---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "./requirements.txt"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"

  - package-ecosystem: "npm"
    directory: "/tests"
    schedule:
      interval: "daily"
    labels: [test]
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "github-actions"
    directory: "/tests"
    schedule:
      interval: "daily"
    labels: [test]
    ignore:
      - dependency-name: "*"
