---
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: src/.*\.py
        name: Formatting Python
      - id: black
        files: src/.*\.py
        # We want this hook to be part of "lint" so that if we run
        # `pre-commit run lint` we include this hook
        alias: lint
        name: Checking Python formatting
        args:
          - --check
          - --diff

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.5
    hooks:
      - id: pylint
        alias: lint
        name: Lint Python (CLI)
        files: src/.*\.py
        additional_dependencies:
          - 'requests~=2.32.3'
          - 'GitPython~=3.1.44'
          - 'pyunpack~=0.3'
          - 'patool~=4.0.0'
          - 'click~=8.1.8'
          - 'gitpython~=3.1.44'
          - 'python-magic~=0.4.27'
          - 'pydantic~=2.11.2'
          - 'pyyaml~=6.0.2'
