name: "Scality SBOM Action"
description: "Creates an SBOM (Software Bill Of Materials) from your code, and artifacts."
author: "Scality"
branding:
  color: blue
  icon: shield
inputs:
  grype-version:
    description: "The version of grype to use"
    required: false
    default: ""
    type: string

  syft-version:
    description: "The version of syft to use"
    required: false
    default: ""
    type: string

  trivy-version:
    description: "The version of trivy to use"
    required: false
    default: ""
    type: string

  ref:
    description: "The git reference to checkout"
    required: false
    default: "main"
    type: string

  path:
    description: "A path to a directory on the filesystem to scan"
    required: false
    default: "."

  file:
    description: "A file on the filesystem to scan"
    required: false

  iso:
    description: "An artifact ISO on the filesystem to scan"
    required: false

  image:
    description: "A container image to scan"
    required: false

  format:
    description: "The SBOM format to export"
    required: false
    default: "cyclonedx-json"

  github-token:
    description: "Authorized secret GitHub Personal Access Token. Defaults to github.token"
    required: false
    default: ${{ github.token }}

  artifact-url:
    description: "The URL for downloading artifacts"
    required: false

  artifact-user:
    description: "The user to use for the SBOM file generated by this action"
    required: false
  
  artifact-password:
    description: "The password to use for the SBOM file generated by this action"
    required: false

  work-dir:
    description: "A directory to store the SBOM"
    required: false
    default: "/tmp/sbom"

runs:
  using: "composite"
  steps:
    - name: Install Python 3
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install python deps
      shell: bash
      run: |
        python3.10 -m pip install -r ${{ github.action_path }}/requirements.txt

    - name: Install dependencies
      shell: bash
      run: | 
          export DEBIAN_FRONTEND=noninteractive && \
          sudo apt-get update && \
          sudo apt-get install --no-install-recommends -y \
          file \
          jq \
          p7zip-full \
          python3-distutils

    - name: Install grype
      shell: bash
      env:
        GRYPE_VERSION: ${{ inputs.grype-version }}
      run: |
        python3 ${{ github.action_path }}src/install.py grype ${{ env.GRYPE_VERSION }}

    - name: Install syft
      shell: bash
      env:
        SYFT_VERSION: ${{ inputs.syft-version }}
      run: |
        python3 ${{ github.action_path }}src/install.py syft ${{ env.SYFT_VERSION }}

    - name: Install trivy
      shell: bash
      env:
        TRIVY_VERSION: ${{ inputs.trivy-version }}
      run: |
        python3 ${{ github.action_path }}src/install.py trivy ${{ env.TRIVY_VERSION }}

    # - name: Checkout repo
    #   if: ${{ inputs.ref }}
    #   uses: actions/checkout@v4
    #   with:
    #     ref: ${{ inputs.ref }}
    #     output: ${{ inputs.work-dir }}/repo/{{ github.repository }}

    # - name: Run the scan of provided repo
    #   shell: bash
    #   if:
    #     - ${{ inputs.path }}
    #   run: python3 ${{ github.action_path }}/src/main.py scan --path ${{ inputs.path }}

    # - name: Download artifacts
    #   shell: bash
    #   run: python3 ${{ github.action_path }}/src/main.py download ${{ inputs.artifact-url }} ${{ inputs.artifact-user }} ${{ inputs.artifact-password }}
    #   if: ${{ inputs.artifact-url }}
    #   with:
    #     artifact-url: ${{ inputs.artifact-url }}
    #     artifact-user: ${{ inputs.artifact-user || '' }}
    #     artifact-password: ${{ inputs.artifact-password || '' }}

    # - name: Run the scan for iso
    #   run: ${{ github.action_path }}/src/main.py scan --iso ${{ inputs.file }}
    #   shell: bash
    #   if: ${{ inputs.file }}
    #   with:
    #     file: ${{ inputs.file }}
