# action.yml
name: 'sbom'
description: 'Greet someone and record the time'
inputs:
  version:
    required: true
    type: string
  # Add additional required inputs
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.artifacts_url }}
