name: "Scality SBOM Action"
description: "Creates an SBOM (Software Bill Of Materials) from your code, and artifacts."
author: "Scality"
branding:
  color: blue
  icon: shield
inputs:
  grype-version:
    description: "The version of grype to use"
    required: false
    default: ""

  syft-version:
    description: "The version of syft to use"
    required: false
    default: ""

  trivy-version:
    description: "The version of trivy to use"
    required: false
    default: ""

  target:
    description: "The target to scan"
    required: false
    default: "."

  format:
    description: "The SBOM format to export"
    required: false
    default: "cyclonedx-json"

  output_dir:
    description: "A directory to store the SBOM"
    required: false
    default: "/tmp/sbom"

runs:
  using: "composite"
  steps:
    - name: Install Python 3
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install python deps
      shell: bash
      run: |
        python3.10 -m pip install -r ${{ github.action_path }}/requirements.txt

    - name: Install dependencies
      shell: bash
      run: | 
          export DEBIAN_FRONTEND=noninteractive && \
          sudo apt-get update && \
          sudo apt-get install --no-install-recommends -y \
          file \
          jq \
          p7zip-full \
          python3-distutils

    - name: Run the scan
      shell: bash
      run: python3 ${{ github.action_path }}/src/main.py
