name: "Install Syft"
description: "Install Syft"

runs:
  using: "composite"
  steps:
    - name: Install deps
      run: |
        export DEBIAN_FRONTEND=noninteractive && \
        curl -O -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh && \
        sudo sh install.sh -b /usr/local/bin
