name: "Install Skopeo"
description: "Install Skopeo and other dependencies"

runs:
  using: "composite"
  steps:
    - name: Install deps
      run: |
        export DEBIAN_FRONTEND=noninteractive && \
        sudo apt-get update && \
        sudo apt-get install --no-install-recommends -y \
        skopeo
