name: Update Scanners

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-scanners:
    runs-on: ubuntu-24.04
    steps:

      - name: Create github token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ACTIONS_APP_ID }}
          private-key: ${{ secrets.ACTIONS_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install requests

      - name: Update scanner versions
        run: python .github/scripts/update_scanners.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: pr
        with:
          title: Dependency update
          branch: feature/deps-update
          commit-message: ":arrow_up: Update scanner versions"
          token: ${{ steps.app-token.outputs.token }}
